language: python

services:
  - docker

matrix:
  include:
    - os: linux
      dist: bionic

before_install:
  # LINUX
  - sudo apt update
  - sudo apt install -y python3 python3-pip
  - pip install -r requirements.txt
script:
  - docker build .

cache:
  directories:
  - $HOME/travis_cache
