language: python

services:
  - docker

matrix:
  include:
    - os: linux
      dist: bionic

before_install:
  # LINUX
  - sudo apt update
script:
  - docker build .

cache:
  directories:
  - $HOME/travis_cache
